Repository ads-unigrade-2019-1/MWScanner, pull requests merged in 2019-04, with the labels that each got.

#9 TF2.2-Discipline-Extraction
  .gitignore
  mwscanner.py
  mwscanner/Campus.py
  mwscanner/Class.py
  mwscanner/Course.py
  mwscanner/Departament.py
  mwscanner/Discipline.py
  mwscanner/Habilitation.py
  mwscanner/Mixins.py
  mwscanner/__init__.py
  requirements.txt
Labels: Tarefa

#10 FIX - Correção de configuração do codeclimate
  .codeclimate.yml
Labels: Bug

#12 FIX - Extração de créditos das disciplinas
  .codeclimate.yml
  mwscanner/Discipline.py
Labels: Refatoração

#13 TAREFA 2.5 - Implementar a automatização de coleta e deploy dos dados para a API
  .gitlab-ci.yml
  databaseConfig/SaveData.py
  databaseConfig/classDatabase.py
  databaseConfig/coursesDatabase.py
  databaseConfig/dbConnection.py
  databaseConfig/departamentDatabase.py
  databaseConfig/departmentDatabase.py
  databaseConfig/disciplineDatabase.py
  databaseConfig/habilitationDatabase.py
  mwscanner.py
  mwscanner/Campus.py
  mwscanner/Course.py
  mwscanner/Department.py
  mwscanner/Discipline.py
  mwscanner/Habilitation.py
  mwscanner/Mixins.py
  requirements.txt
Labels: Tarefa

#14 FIX - Refatoração campus nas classes
  databaseConfig/SaveData.py
  databaseConfig/classDatabase.py
  databaseConfig/coursesDatabase.py
  databaseConfig/dbConnection.py
  databaseConfig/departmentDatabase.py
  databaseConfig/disciplineDatabase.py
  databaseConfig/habilitationDatabase.py
  mwscanner/Class.py
  mwscanner/Discipline.py
Labels: Refatoração
